### ISSUE TITLE
Configure MySQL logging to go to a file

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/aws-broker#127]
In order to support downloading of MySQL logs for customers, we need MySQL to log to a file.

## Acceptance Criteria
* [ ] GIVEN MySQL instances that are logging
  WHEN logs are generated
  THEN they are written to a file
  AND downloadable via the AWS CLI

--- 

## Security considerations

Logs are currently stored within AWS. This will not change as logs will remain in AWS, just in logs instead of a table. Postgres already logs to files now.

## Implementation sketch

Setting changes: https://aws.amazon.com/premiumsupport/knowledge-center/rds-download-instance-logs/

* [ ] Update existing standalone MySQL RDS instances to log to a file
* [ ] Update the broker to ensure logging to a file is the default setting for standalone instances

**Comment by markdboyd** [comment]
Superseded by

https://github.com/cloud-gov/aws-broker/issues/372
https://github.com/cloud-gov/private/issues/957
