### ISSUE TITLE
Support opt-in of shipping RDS logs to an S3 bucket

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/aws-broker#128]
In order to support customers needing RDS logs in external (non cloud.gov) systems, customers with standalone RDS instances need to be able to opt-in to log shipping to S3.

The scope of this story is only to opt in to the configuration. It is does not encompass shipping logs.

## Acceptance Criteria
* [ ] GIVEN a customer with a dedicated RDS instance (not shared)
  WHEN the customer needs logs shipped to S3
  THEN the customer can opt-in

--- 

## Security considerations

None. This should just be a configuration setting in the broker DB. The scope of this story is only to opt-in to the configuration. It does not encompass shipping logs.

## Implementation sketch

* [ ] Enable a configuration setting to be passed to the broker on service instance creation or update

**Comment by markdboyd** [comment]
Superseded by

https://github.com/cloud-gov/aws-broker/issues/372
https://github.com/cloud-gov/private/issues/957
