### ISSUE TITLE
Provision a bucket for RDS logs

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/aws-broker#130]
In order to ship RDS logs to a customer via S3, the broker should be able to provision a bucket if necessary.

## Acceptance Criteria
* [ ] GIVEN a customer opting in to RDS log shipping to S3 \
  AND without an existing bucket for RDS logs in the space \
  WHEN the customer opts in to ship RDS logs \
  THEN the broker provisions an S3 bucket (service instance) in the customer space 

* [ ] GIVEN a customer opting in to RDS log shipping to S3 \
  AND with an existing bucket for RDS logs in the space \
  WHEN the customer opts in to ship RDS logs \
  THEN the broker uses the existing S3 bucket (service instance) in the customer space 

--- 

## Security considerations

By leveraging the broker, we minimize any security risks (they are the same with any other S3 bucket). Because the service instance is in the customer space, the customer can generate bindings and service keys as needed.

**Comment by markdboyd** [comment]
Superseded by

https://github.com/cloud-gov/aws-broker/issues/372
https://github.com/cloud-gov/private/issues/957
