### ISSUE TITLE
Investigate: Scoping RDS logs to a customer

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/aws-broker#131]
In order to ingest RDS logs, we need a strategy to ensure RDS logs are scoped to a customer. 

Question:
- Can the `org` setting be applied on a "per file basis"?
- Do we have to modify each log entry to include an "org-id"?

--- 

## Security considerations

This is a research task to define the correct method to ensure the security of customer data.

**Comment by markdboyd** [comment]
Superseded by

https://github.com/cloud-gov/aws-broker/issues/372
https://github.com/cloud-gov/private/issues/957
