### ISSUE TITLE
Investigate: What is the impact on indexing if we ingest RDS logs?

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/aws-broker#132]
In order to determine the feasibility of ingesting RDS logs in Kibana, we need to understand the impact of RDS logs on indexes.

The purpose of this task is to investigate and document any potential impacts.

--- 

## Security considerations

None

## Implementation sketch

Try it?

**Comment by markdboyd** [comment]
Superseded by

https://github.com/cloud-gov/aws-broker/issues/372
https://github.com/cloud-gov/private/issues/957
