### ISSUE TITLE
Log exporter: Support downloading of RDS logs from AWS 

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/aws-broker#134]
In order to ship RDS logs to customers, we need a log exporter application that can download a customer's RDS logs from AWS using the ACL.

## Acceptance Criteria

The application needs to:

- [ ] support downloading RDS log archive files via the AWS CLI
- [ ] only download logs for specific RDS instances
- [ ] track the last downloaded log archive for each RDS instance
- [ ] leverage the minimum needed RDS credentials to achieve downloading
- [ ] support downloading on a configurable schedule (ie every 2 hours)

--- 

## Security considerations

The application should leverage the least privileged credentials required to download logs.

**Comment by markdboyd** [comment]
Superseded by

https://github.com/cloud-gov/aws-broker/issues/372
https://github.com/cloud-gov/private/issues/957
