### ISSUE TITLE
Log-exporter: Support sending RDS logs to Kibana

### ISSUE THREAD

**Issue by spgreenberg** [cloud-gov/aws-broker#136]
In order to support shipping RDS logs to Kibana, the log-exporter needs to support sending downloaded archives to Kibana ingestors.

Depends on: 
- https://github.com/cloud-gov/aws-broker/issues/134
- https://github.com/cloud-gov/aws-broker/issues/131
- https://github.com/cloud-gov/aws-broker/issues/132

## Acceptance Criteria

The log-exporter needs to:

- [ ] Be able to send downloaded archives Kibana ingestors
- [ ] Customer RDS logs must be scoped correctly to a single org.

--- 

## Security considerations

See: https://github.com/cloud-gov/aws-broker/issues/132

**Comment by markdboyd** [comment]
Superseded by

https://github.com/cloud-gov/aws-broker/issues/372
https://github.com/cloud-gov/private/issues/957
