### ISSUE TITLE
Retain Elasticsearch Service backups for 14 days after deletion (1/18)

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/aws-broker#162]
In order to maintain backups as documented, we want to keep backups of Elasticsearch instances for 14 days after service deletion

## Acceptance Criteria
 * [ ] GIVEN a aws-es service instance \
    WHEN a user calls cf delete-service on the instance \
    AND the broker finishes deleting the service instance \
    THEN existing, automated backups are still available for 14 days \
    AND existing automated backups are deleted after 15 days

## Security considerations

Protects data in case of accident or malicious deletion

## Implementation sketch
* [ ] check if this is possible automatically using current AWS API calls
* [ ] reach out to AWS rep if not
* [ ] consider alternatives if AWS rep doesn't provide timeline for this to be possible with current API

**Comment by rbogle** [comment]
Notes/Research on Elastic/Open search data retention:
https://docs.google.com/document/d/1Lu00kxNgu-hDlOAKzLGH62v9WkZxQ2dF6PJTZgtmyoM/edit?usp=sharing
