### ISSUE TITLE
Retain Redis backups for 14 days after service deletion (1/18)

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/aws-broker#163]
In order to maintain backups as documented, we want to keep backups of elasticache instances for 14 days after service deletion

## Acceptance Criteria
* [ ] GIVEN a aws-redis service instance \
    WHEN a user calls cf delete-service on the instance \
    AND the broker finishes deleting the service instance \
    THEN existing, automated backups are still available for 14 days \
    AND existing automated backups are deleted after 15 days

## Security considerations

Protects data in case of accident or malicious deletion

## Implementation sketch
* [ ] check if this is possible automatically using current AWS API calls
* [ ] reach out to AWS rep if not
* [ ] consider alternatives if AWS rep doesn't provide timeline for this to be possible with current API

**Comment by LindsayYoung** [comment]
After elasticsearch is done we can work on this
