### ISSUE TITLE
allow advanced options on Elasticsearch service instances

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/aws-broker#172]
In order to support more complex elasticsearch use cases, we want to allow users to specify [advanced options](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-advanced-options) for elasticsearch

## Acceptance Criteria
* [ ] WHEN a user requests a new elasticsearch service instance \
  AND the user supplies "advanced options" in the configuration body \
  THEN the broker should validate the keys against an allowlist \
  AND the broker should validate the data type of the values \
  AND the broker should create the service instance with the specified advanced options
* [ ] GIVEN an update request \
  WHEN a user calls update \
  AND the user supplies "advanced options" in the configuration body \
  THEN the broker should validate the keys against an allowlist \
  AND the broker should validate the data type of the values \
  AND the broker should update the service instance to have the specified advanced options

## Optional/consider
We might validate the _values_ of the advanced options to give faster feedback for invalid options, instead of waiting on AWS. 

--- 

## Security considerations
None

**Comment by ChrisMcGowan** [comment]
After reviewing the AWS API options used to create/modify AWS ES instances, cloud.gov has confirmed that the following values can be adjusted via this broker:

- `Fielddata cache allocation` - _Specifies the percentage of heap space that is allocated to fielddata_  - defaults to `20`
- `Max clause count` - _Specifies the maximum number of allowed boolean clauses in a query_  - defaults to `1024`

**Comment by mheadd** [comment]
Assuming that this was pulled into a sprint, do we have a sense of how long it would take to implement? A customer is asking about when this feature may become available and @LindsayYoung wanted to provide an estimate.

**Comment by bengerman13** [comment]
This is pulled into a sprint :)

I think it's probably only a day or two of work for someone comfortable in the codebase (@soutenniza or @ccostino I think, both of whom are tied up with other things). Probably add a day for someone who needs to get their bearings here

**Comment by LindsayYoung** [comment]
If it is possible, lets try to get this done by Oct 8th
