### ISSUE TITLE
Upgrade shared and internal DB in prod from pg 9.5 (2/8)

### ISSUE THREAD

**Issue by rbogle** [cloud-gov/aws-broker#206]
Upgrade your RDS for PostgreSQL 9.5 databases before Feb 16, 2021
The RDS for PostgreSQL 9.5 end-of-life date is approaching. Your database is using a version that must be upgraded to 12 or higher as soon as possible. We plan to automatically upgrade RDS for PostgreSQL 9.5 databases to 12 starting February 16, 2021 00:00:01 AM UTC.

For more information, see the RDS for PostgreSQL deprecation timeline in the Amazon RDS forum.

**Comment by ccostino** [comment]
[A draft notice for maintenance](https://docs.google.com/document/d/1q77zsmm8PJobmj4hkGg_6L29GbfQD0htN7Ouo8oGGO8/edit#) has been written and will be sent out the morning of 2/3/2022.  Maintenance is being scheduled 2/8/2022 - 2/10/2022 to upgrade all of the internal production databases.
