### ISSUE TITLE
Allow users to restore RDS snapshots from backup

### ISSUE THREAD

**Issue by jmcarp** [cloud-gov/aws-broker#21]
We currently store database snapshots, created at the default interval, but don't give users a way to restore from snapshots. If a user requested a restore from a snapshot, we'd have to restore manually and do some extra work to make the restored database available via the broker. To fix, we can expose snapshot ID or timestamp as an optional parameter to provision, and/or allow users to restore to a point in time during update.

Can be changed on this repo or https://github.com/cf-platform-eng/rds-broker.

**Comment by wz-gsa** [comment]
Closing due to environmental changes
