### ISSUE TITLE
Create recurring meeting for updating our catalog's service offerings

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/aws-broker#233]
In order to keep our catalog of services and their versions up to date, we want to create a recurring quarterly meeting to update our service offerings for RDS, ElasticCache, and OpenSearch (formerly AWS Elasticsearch)

## Acceptance Criteria
* [ ] Create quarterly meeting
* [ ] Add last supported Elasticsearch version 7.10
* [ ] Add OpenSearch versions

--- 

## Security considerations
None

**Comment by bengerman13** [comment]
I think this is a good start - I wonder if we should make it automagic instead, though. Worth considering after a couple iterations of the meeting
