### ISSUE TITLE
[Research] Investigate cloud-service-broker and the aws-brokerpak as replacement for aws-broker

### ISSUE THREAD

**Issue by rbogle** [cloud-gov/aws-broker#237]
In order to provide additional and more robust services to clients as well as improve features and maintainability of existing services, we want to investigate the cloud-service-broker framework as a potential replacement for our aws brokers.

## Research Tasks
* [ ] Automation and maintainability of CSB and AWS brokerpak in CF
* [ ] Feature compare AWS BP support for RDS -- see aws-broker backlog for pending bugs/features needed
* [ ] AWS BP ease of adding new aws services ( EFS, SNS, SMS, Dynamodb etc)
* [ ] Feature compare AWS BP support for Opensearch
* [ ] Feature compare AWS BP support for Elasticache (Redis)
* [ ] Feature compare AWS BP support for S3

[cloud-service-broker](https://github.com/cloudfoundry/cloud-service-broker)
[aws brokerpak](https://github.com/cloudfoundry/csb-brokerpak-aws)
--- 

## Security considerations
note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story

**Comment by bengerman13** [comment]
I think the big snags we'll hit here are around lifecycle. I'm not totally sure, but this might also block our longstanding desire to make it possible to restore from a backup via the broker

**Comment by markdboyd** [comment]
Superseded by https://github.com/cloud-gov/product/issues/2943
