### ISSUE TITLE
Allow increasing size when RDS db full

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/aws-broker#241]
In order to allow self-service recovery from full databases, customers want to be able to increase allocated storage when the database is full

## Acceptance Criteria
* [ ] GIVEN a full database \
  WHEN a user calls `update-service` \
  AND the user provides a storage size that is at least 10% larger than their current size \
  THEN the update succeeds
* [ ] GIVEN a full database \
  WHEN a user calls `update-service` \
  AND the user provides a storage size that not at least 10% larger than their current size \
  THEN the update fails \
  AND the update failure message indicates the database is full \
  AND the update failure message instructs the user of the minimum acceptable size
* [ ] GIVEN a full database \
  WHEN a user calls `update-service` \
  AND the user does not provide a size parameter \
  THEN the update fails \
  AND the update failure message indicates the database is full \
  AND the update failure message instructs the user of the minimum acceptable size

--- 

## Security considerations
none

## Implementation sketch
some clues in the aws docs:
-  https://aws.amazon.com/premiumsupport/knowledge-center/rds-out-of-storage/
- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PIOPS.StorageTypes.html#USER_PIOPS.ModifyingExisting

I believe the trick is that we need to provide _only_ the updated storage parameter *and* set apply immediately to true

**Comment by jameshochadel** [comment]
Re. the last acceptance criterion: Am I understanding correctly that if the database is full, the user may not perform other database modifications via `update-service` unless they also resize the database? E.g. they can't change their instance class alone.

**Comment by bengerman13** [comment]
right. I *think* the most user-friendly way to do this is:
- if the user updates their db and does not change the size, fail with friendly message
- if the user updates their db and only changes size, update size accordingly
- if the user updates their db and changes size and another parameter, change size then the other thing

the third thing, though, might be kind of unexpected for users, so _maybe_ we should refuse and make the user serialize those tasks

**Comment by jameshochadel** [comment]
A brief update on this: I have an implementation ready and am working on a smoke test for the new feature. To support that test, which will load a pre-populated database from an s3 bucket, I am working on deploying the `s3-broker` to our dev environment. The broker itself has been deployed there, but its acceptance tests are failing. I am working on diagnosing the failure.

**Comment by mogul** [comment]
The S3 broker now exists in the dev environment. James is working on tests for this functionality.

**Comment by markdboyd** [comment]
For now, we can descope this work and revisit it if the need recurs
