### ISSUE TITLE
Enable encryption at rest on all Elasticsearch/Opensearch plans

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/aws-broker#253]
In order to improve security, we want to enable encryption at rest on all Elasticsearch/Opensearch broker plans.

--- 

## Security considerations

Guaranteeing encryption at rest should be a improvement in security

## Implementation sketch

Should just be a matter of setting `encryptAtRest: true` for all plans. Seems like there are only a couple of plans with `encryptAtRest: false`

https://github.com/cloud-gov/aws-broker/blob/master/catalog-template.yml#L1260
https://github.com/cloud-gov/aws-broker/blob/master/catalog-template.yml#L1289

**Comment by pburkholder** [comment]
I'm removing the squad-assurance label since there's nothing actionable on it, but I am following this issue.

**Comment by rbogle** [comment]
@JasonTheMain this might be a good one to work on next.

**Comment by JasonTheMain** [comment]
all plans are now set to True

**Comment by markdboyd** [comment]
@JasonTheMain 

I think there are still plans with `encryptAtRest: false`?

https://github.com/cloud-gov/aws-broker/blob/master/catalog-template.yml#L1355
https://github.com/cloud-gov/aws-broker/blob/master/catalog-template.yml#L1388

**Comment by JasonTheMain** [comment]
closed with commit[  ](https://github.com/cloud-gov/aws-broker/commit/b0211a58aeb3d36a9f540bbb946bf7521030ed37)

**Comment by rbogle** [comment]
We will also need to handle updating existing instances that are not EaR enabled, should we make that a new issue?

**Comment by JasonTheMain** [comment]
I was thinking we could, this is a quick issue just to update what we have, handling updating existing issues should be a new ticket because itll take slightly more time
