### ISSUE TITLE
Update storage/volume types from gp2 to gp3 across all plans

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/aws-broker#255]
In order to optimize costs, we should update EBS storage from gp2 to gp3 volumes across all of our brokered plans

--- 

## Security considerations

There are no meaningful security differences from gp2 to gp3 volumes, as far as I know, just cost and performance optimizations.

https://aws.amazon.com/ebs/general-purpose/#:~:text=gp3%20offers%20SSD%2Dperformance%20at,improving%20performance%20and%20reducing%20costs.

## Implementation sketch

- [ ] Update all plans in catalog to use gp3 for `storage_type` instead of gp2
- [ ] Update all plans in catalog to use gp3 for `volumeType` instead of gp2

**Comment by JasonTheMain** [comment]
ill test changing plans and start investigating the difference for a little spare fuin

**Comment by JasonTheMain** [comment]
Following issues are a blocked for now https://github.com/hashicorp/terraform-provider-aws/issues/28271

**Comment by JasonTheMain** [comment]
found bugs, will update when working

**Comment by JasonTheMain** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/28160 blocked issue for now

**Comment by etiennechabert** [comment]
@JasonTheMain you should not have any more blocker to adopt gp3.

If using: https://github.com/terraform-aws-modules/terraform-aws-rds use the last version:
https://github.com/terraform-aws-modules/terraform-aws-rds/releases/tag/v5.2.2

Default values have been fixed, allowing a smooth transition to gp3.

**Comment by markdboyd** [comment]
Closing this and opening #271 to handle converting existing databases to gp3

**Comment by Ephraim-G** [comment]
closed per #330
