### ISSUE TITLE
Update Redis plans to default to version 6.2

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/aws-broker#258]
In order to support users request the latest versions of Redis for specific project needs, we want to update our Redis plans in the broker to default to version 6.2.

## Acceptance Criteria

* [x] Creating a Redis instance with the broker defaults to Redis v6.2
* [x] You can specify an older version, Redis 5.0.6, when creating a Redis instance

--- 

## Security considerations

None. Supporting later Redis versions should be more secure and extend the lifespan of security patching.

## Implementation sketch

* [x] Update all redis plans in the catalog to default to version 6.2: https://github.com/cloud-gov/aws-broker/blob/master/catalog-template.yml#L1220
* [x] [Like we do for Postgres plans](https://github.com/cloud-gov/aws-broker/blob/master/catalog-template.yml#L974-L976), update Redis broker code (if necessary) to support specifying an older engine version (5.0.6) when creating a service instance
* [x] Update the website page on Redis to note 6.2 is now the default: https://cloud.gov/docs/services/aws-elasticache/
* [x] Work with compliance team to ensure versions are correct in SSP Services tables
* [x] Review Redis 6 release notes for any other steps necessary for service security

**Comment by JasonTheMain** [comment]
all versions are shown working
