### ISSUE TITLE
Add support for Opensearch versions

### ISSUE THREAD

**Issue by dzaslavskiy** [cloud-gov/aws-broker#259]
We would like to be able to use more recent versions of elasticsearch/opensearch. Specifically Opensearch 1.1

## Acceptance Criteria

- [x] Able to specify opensearch version 1.1 when creating elasticsearch instance

**Comment by rbogle** [comment]
## Notes / Tasks

- [ ] Timebox: ( 1 Week)  research adding Opensearch to the ES-Broker, and any required API differences and setting changes
- [ ] Timebox: (1 week) assess compliance implications with Compliance team, is SCR needed, are settings/config change required
- [ ] Timebox ( 1+ sprint) implement changes, test and release.

**Comment by JasonTheMain** [comment]
Had compliance implications meeting, should have the same compliance matrix as the elastisearch.

**Comment by JasonTheMain** [comment]
see commit https://github.com/cloud-gov/aws-broker/commit/ad4283d9769a02a826310126ac9313defdabaaf5 for release
