### ISSUE TITLE
Support enabling pg_cron extension

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/aws-broker#270]
## Background

A customer requested the ability to use the pg_cron extension databases with their brokered RDS PostgreSQL databases. 

To enable the pg_cron extension for a database requires setting a parameter in a custom parameter group: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL_pg_cron.html

## Implementation

We need to update the AWS broker to include a command-line option for enabling the pg_cron extension when creating/updating a database service.

We should ensure that this option is only accepted when the database is a PostgreSQL database.

## Acceptance criteria 

- [x] AWS broker is updated with a command line option to support enabling pg_cron
- [x] Testing demonstrates that broker can be used to enable pg_cron when:
  - [x] creating a database
  - [x] updating a database
- [x] Update public documentation to note the new command-line option: https://cloud.gov/docs/services/relational-database/

**Comment by rbogle** [comment]
@markdboyd what do you think we should do with this one?

**Comment by markdboyd** [comment]
@rbogle I was going to move forward with doing this one after my current broker ticket (#269), because I don't think it's much work. But what do you think?

**Comment by rbogle** [comment]
Sounds good!

**Comment by markdboyd** [comment]
This has been deployed to prod and the public documentation has been updated. Closing.
