### ISSUE TITLE
Supporting updated versions of PostgreSQL

### ISSUE THREAD

**Issue by ArsHaider** [cloud-gov/aws-broker#281]
In order to support users request for newer versions of PostgreSQL for specific project needs, we want to update our PostgreSQL offerings to include versions 13, 14, and 15.

## Acceptance Criteria

- [x] Update all PostgreSQL plans in the catalog to include 13, 14, and 15 for approved major versions: https://github.com/cloud-gov/aws-broker/blob/c806545156ab65f97a4f9ece35d747f9b70e494c/catalog-template.yml#L37-L40
- [x] Update the default on all our PostgreSQL plans to the version 15: https://github.com/cloud-gov/aws-broker/blob/c806545156ab65f97a4f9ece35d747f9b70e494c/catalog-template.yml#L41
  - [x] Update plan descriptions to note v15: https://github.com/cloud-gov/aws-broker/blob/c806545156ab65f97a4f9ece35d747f9b70e494c/catalog-template.yml#L24
- [x] Update the website page on [RDS](https://cloud.gov/docs/services/relational-database/) to note the newer available versions (13, 14, 15) and new default (15)
- [x]  Work with the compliance team to ensure versions are correct in SSP Services tables. 
- [x] Review the release notes for the newer available version (13, 14, 15) any other steps necessary for service security.
- [x]  After merging and deploying aws-broker changes to stage, confirm that smoke tests are still passing
- [x] Promote changes to production and confirm that a new RDS database can be created and defaults to PostgreSQL 15
  - [x] Confirm that you can still create a database in production using an older version (12)
- [x] Publish cloud.gov news post announcing the availability of PostgreSQL 13, 14, 15 on the platform

**Comment by kbighorse** [comment]
as of today, `15.2` is the current minor version: https://www.postgresql.org/support/versioning/
