### ISSUE TITLE
Support seamless brokered service credential rotation 

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/aws-broker#290]
As a consumer of the AWS RDS broker,
I should be able to rotate the credentials used for database access,
with an `update-service` command
and an application restage.

## Acceptance Criteria

- [x] Demonstration of the above capability
- [ ] Walking through the process with at least 3 customers

**Comment by markdboyd** [comment]
Documentation PR: https://github.com/cloud-gov/cg-site/pull/2283

**Comment by markdboyd** [comment]
A customer confirmed that the credential rotation worked for them, so I'm going to close this ticket and we can reopen it if any customers subsequently have issues with this feature
