### ISSUE TITLE
Add AWS Resource Tagging to new Elasticache/Redis plans via aws service broker

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/aws-broker#336]
To better track our resource usage by customer, we need to have the aws broker add tags to all user created service instances so we can track customer service usage.

The following tags need to be defined to each new instance created by the broker _**note case and caps:**_

- Instance GUID
- Plan GUID
- Service GUID
- Organization GUID
- Space GUID
- client
- environment
- service

## Acceptance Criteria

- [x] Add code to broker for assigning tags on any new/update service instance operation
- [x] Validate tags are being created on new instances
- [x] Validate in AWS Cost Explorer that test instances with tags are showing up

**Comment by markdboyd** [comment]
I have verified by manual testing that the tags are being applied properly to new Elasticache/Redis plans. I just activated the new cost tags in the cost explorer and I'll verify tomorrow that Redis instances can be properly grouped by Organization name

**Comment by markdboyd** [comment]
I have validate that the new tags appear in the cost explorer and costs can be filtered/grouped by them. 

**Important note: since the tags were just activated on January 17, you cannot filters/group costs by the new tags for Elasticache services before that day.**
