### ISSUE TITLE
Retire/migrate db.t2 and db.m4 RDS Instance classes

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/aws-broker#350]
With RIs for `db.t2` and `db.m4` expiring on 1/5/24 and AWS has removed the ability to purchase new ones, CG needs to migrate all RDS DBs on these classes to `db.t3` and `db.m5` which have RIs to save on average 35% off the monthly RDS bill

## Notes

- See @cweibel for a RDS dump of effected instances: 139 total effected, 122 production customers, the rest are CG
- 9 of the CG ones are created by TF so upgrade path needs to be tested as these effect BOSH, CF, and some brokers
- Testing a brokered DB `db.t2` and moving it to `db.t3` via the RDS console takes around 6 min with 3 of those min being an outage on connectivity.  This was for MySql
- CG Biz folks are working on customer communications
-  Some customers might accept the instance migration taking place during the weekly AWS maintenance window for their instance - those that can't will need to schedule the outage with CG support during normal support hours, or customers can create new service instances and migrate their data and instance themselves
- Starting Jan 2024 this reduction of legacy RIs adds 35% to our RDS bill so the longer the conversion takes, the more it costs

## Acceptance Criteria

- [x] Test TF migration steps
- [x] Test AWS Scheduled maintenance upgrade for all flavors (t2/m4 - MySql & t2/m4 - Postgres)  (manual do it now has been tested for MySql-t2, remaining flavors need testing)
- [x] Work with CG Biz and CG Support on communications to customers needing to perform migrations

**Comment by cweibel** [comment]
We did the bulk of the migrations to this point, handing the remaining ones to the success team
