### ISSUE TITLE
S3 service should have a plan for provisioning FIPS compliant URI

### ISSUE THREAD

**Issue by vshetty001** [cloud-gov/aws-broker#84]
In order to have applications follow FIPS compliance standards when connecting to AWS S3 Rest API, FDIC Security wants the URI that is provisioned as part of the S3 service key to be FIPS compliant.  The workaround as this point is for the application to ignore the URI in the service key and manually use the FIPS compliant URI (provided by AWS). A better idea is to update the URI to be FIPS compliant or include a plan which can provide that 

## Acceptance Criteria

  WHEN creating a AWS service Instance \
  AND creating a service key or binding the instance to application\
  THEN provide option for the URI to be FIPS compliant \
  
--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] [first thing to do]
* [ ] [another thing to do]

**Comment by bengerman13** [comment]
This is a duplicate of cloudfoundry-community/s3-broker#37 

@vshetty001 we'll track this over there.
