### ISSUE TITLE
Add to DB credentials block for greater compatibility

### ISSUE THREAD

**Issue by mogul** [cloud-gov/aws-broker#87]
In order to deploy and use existing code that works with Pivotal and AWS' RDS brokers, cloud.gov customers want the DB name to be provided in an additional "name" field in VCAP_SERVICES.

Context: A couple of times previously, I've run into a problem where code written by people using other CF deployments doesn't work with bound cloud.gov RDS instances. [It happened again today.](https://github.com/pivotal/cloud-service-broker/issues/49#issuecomment-659507763)

(Leaving everything below for the team to fill out.)

---
## Acceptance Criteria
* [ ] GIVEN [a precondition] \
  AND [another precondition]
  WHEN [test step] \
  AND [test step] \
  THEN [verification step] \
  AND [verification step]

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] [first thing to do]
* [ ] [another thing to do]

**Comment by mogul** [comment]
For reference: Other teams are [not willing to work around this difference](https://github.com/pivotal/cloud-service-broker/issues/49) between cloud.gov's broker and other DB brokers.

**Comment by bengerman13** [comment]
@mogul so the upshot here is change:
```
      "credentials": {
        "db_name": "cgawsbrokerprodk8evyj9pv9fdotd",
        "host": "cg-aws-broker-prodk8evyj9pv9fdotd.ci7nkegdizyy.us-gov-west-1.rds.amazonaws.com",
        "password": "[REDACTED]",
        "port": "3306",
        "uri": "mysql://ux6uzfrqb2f61kei:[REDACTED]@cg-aws-broker-prodk8evyj9pv9fdotd.ci7nkegdizyy.us-gov-west-1.rds.amazonaws.com:3306/cgawsbrokerprodk8evyj9pv9fdotd",
        "username": "ux6uzfrqb2f61kei"
      }
```
to
```
      "credentials": {
        "db_name": "cgawsbrokerprodk8evyj9pv9fdotd",
        "name": "cgawsbrokerprodk8evyj9pv9fdotd",
        "host": "cg-aws-broker-prodk8evyj9pv9fdotd.ci7nkegdizyy.us-gov-west-1.rds.amazonaws.com",
        "password": "[REDACTED]",
        "port": "3306",
        "uri": "mysql://ux6uzfrqb2f61kei:[REDACTED]@cg-aws-broker-prodk8evyj9pv9fdotd.ci7nkegdizyy.us-gov-west-1.rds.amazonaws.com:3306/cgawsbrokerprodk8evyj9pv9fdotd",
        "username": "ux6uzfrqb2f61kei"
      }
```
is that right?

**Comment by mogul** [comment]
Yes, that's right! Just adding the other field with the DB name.
